#! /bin/bash

if [ -z "$1" ]
  then
    echo "Privilege Unspecified"
    exit 1
fi

cp histogram_plot.py ./$1/
cd $1
python3 histogram_plot.py
find . -name '*.dot' | xargs I{} dot -Tsvg {} -o {}.svg 
find . -name '*.svg' -exec google-chrome {} +

